### ISSUE TITLE
Twitter integration

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/alnap#126]
Link feeds view to ALNAP twitter account

**Comment by angievanhegan** [comment]
@pipemanta This one can be moved over into in progress, right? Thanks

**Comment by angievanhegan** [comment]
@russ-manta Please can you check the 'ALNAP to check' criteria? Thanks

**Comment by Maria-alnap** [comment]
@angievanhegan Before closing this, I'll just wait for one of our tweets with an image to see whether that looks OK as well

**Comment by angievanhegan** [comment]
@Maria-alnap Good idea.

**Comment by Maria-alnap** [comment]
@angievanhegan Images are not currently showing up in tweets that have them. See our latest tweet for reference: https://twitter.com/ALNAP/status/888004438383788033

**Comment by angievanhegan** [comment]
@russ-manta I'm glad you waited to catch this! It was displaying originally with the Manta Ray feed and that had images. I wonder what's happening here? 

@russ-manta please can you reassign? Thanks

**Comment by pipemanta** [comment]
@angievanhegan @russ-manta Actually we don't have a solution for this issue, we have the same on other sites, when the tweet include a link doesn't show the image... It's a limitation of the module, we are keeping an eye on it.

**Comment by angievanhegan** [comment]
@pipemanta to have a look at the new version of hte module

**Comment by pipemanta** [comment]
@russ-manta @angievanhegan Fixed with the new patch!

**Comment by angievanhegan** [comment]
@pipemanta Brilliant! You unblocked a thing!! I'll put it over to Maria to review.

**Comment by angievanhegan** [comment]
@Maria-alnap this is ready for you to review. Thanks

**Comment by Maria-alnap** [comment]
@angievanhegan this is now displaying! Yippeee!

**Comment by russ-manta** [comment]
@meldera could you take a quick look at this one with @pipemanta next week. There was an issue with displaying images in tweets which have a link in them which has been partially resolved by applying a patch to the latest module but I think there may still be an issue with only some images being displayed and not all

**Comment by angievanhegan** [comment]
@russ-manta can you talk with @meldera about this one? Thanks

**Comment by russ-manta** [comment]
@meldera can you take a look at this one please? Images are loading erratically in the home twitter feed if a link is included. Let's talk about it before you start

**Comment by nadia847** [comment]
@dave-manta @russ-manta we may have to roll back to twitter module 7.x-5 and live without pictures in the tweets as 7.x-6 is very buggy at the minute. Thoughts?

**Comment by dave-manta** [comment]
@nadia847 not something I feel knowledgeable enough to comment on.

**Comment by nadia847** [comment]
@meldera please roll back to twitter v5

**Comment by meldera** [comment]
Could be related to v6.x not working:

https://www.drupal.org/node/1981472
https://www.drupal.org/node/1936598
https://www.drupal.org/node/2584511
https://www.drupal.org/node/2584539
https://www.drupal.org/node/2833977
https://stackoverflow.com/questions/16374568/php-mysql-bigint-issue
https://stackoverflow.com/questions/13962771/twitter-not-saving-unique-tweet-id

**Comment by russ-manta** [comment]
try different os / version of php?

**Comment by russ-manta** [comment]
@meldera we now have x64 on live and it's pulling in the tweets but not all images can you see if anything can be done?
